common: &common
  host: localhost
  timeout: 5000
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *common
  database: yen_models_development

test: &test
  <<: *common
  database: yen_models_test

cucumber:
  <<: *test

staging:
  <<: *common
  database: yen_models_staging

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: rails
  password: rails
