common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: rails
  password: rails

development:
  <<: *common
  database: yen_models_development

test: &test
  <<: *common
  database: yen_models_test

cucumber:
  <<: *test

staging:
  <<: *common
  database: yen_models_staging

production:
  <<: *common
  database: yen_models_production
